name: Build "turnip"

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to build'
        required: true
        type: string

jobs:
  start_building_turnip:
    runs-on: ubuntu-24.04
    env:
      BUILD_VERSION: ${{ inputs.version }}
    steps:
    - name: Checkout repo
      uses: actions/checkout@v6

    - name: Prepare environment
      run: |
        sudo sed -i 's/^Types: deb$/Types: deb deb-src/' /etc/apt/sources.list.d/ubuntu.sources
        sudo apt update
        sudo apt install build-essential flex bison glslang-tools
        sudo apt install meson-1.5 

    - name: Execute build script
      run: bash ./turnip_builder.sh

    - name: Release "turnip"
      uses: softprops/action-gh-release@v3
      with:
        body: |
          # Turnip ${{ inputs.version }}
          Built from: https://github.com/lfdevs/mesa-for-android-container (`dev/adreno-main` branch)
          
          > [!WARNING]
          > Since the modifications made to the upstream Mesa source code on this branch are mainly targeted at Termux:X11, the drivers built using this branch **may not be suitable for scenarios such as game emulators**.
          
          ## Supported GPUs
          See https://github.com/lfdevs/mesa-for-android-container#compatibility
          
          ## Changelog
          Please refer to the changelog of the corresponding version here: https://github.com/lfdevs/mesa-for-android-container/releases

        tag_name: tu-${{ inputs.version }}
        name: Turnip ${{ inputs.version }}
        files: |
           /tmp/turnip-${{ inputs.version }}.zip
          #  /tmp/turnip-sync-${{ inputs.version }}.zip
